 name: CI

on:
  push:
    branches: ["**"]     # toutes les branches
  pull_request:           # et toutes les PR

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint (ruff)
        run: ruff check .

      - name: Run tests (pytest)
        run: pytest -q

      - name: Build Docker image
        run: docker build -t fastapi-ci-cd:${{ github.sha }} .
